# Generated by Django 3.2.8 on 2021-10-30 14:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiredDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 16, 6, 6, 981852)),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biography', models.TextField()),
                ('Country', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator])),
                ('Contact', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator])),
                ('HeaderImage', main.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('Avatar', main.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('isSeller', models.BooleanField(default=False)),
                ('isManager', models.BooleanField(default=False)),
                ('loyaltyPoints', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
