# Generated by Django 3.2.8 on 2021-10-30 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211030_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiredDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 18, 16, 22, 335213)),
        ),
    ]
