# Generated by Django 3.2.8 on 2021-10-30 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_coupon_expireddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiredDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 21, 54, 263562)),
        ),
    ]
