# Generated by Django 3.2.8 on 2021-10-31 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_coupon_expireddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiredDate',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 11, 30, 14, 45, 44, 946799), default=datetime.datetime(2021, 11, 30, 14, 45, 44, 946799)),
        ),
    ]
