# Generated by Django 3.2.8 on 2022-01-14 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220114_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_name',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suburb',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator]),
        ),
    ]
