# Generated by Django 3.2.8 on 2022-01-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20220114_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='surburb',
            new_name='suburb',
        ),
    ]
