# Generated by Django 3.2.8 on 2022-01-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_surburb_shipment_suburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='street_name',
            new_name='street_address',
        ),
    ]
