# Generated by Django 3.2.8 on 2021-10-30 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator])),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator])),
                ('Quantity', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('isSpecial', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('Description', models.TextField()),
                ('FrontImage', main.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('RearImage', main.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('Categories', models.ManyToManyField(related_name='productCategories', to='products.Category')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starsCount', models.IntegerField(default=0)),
                ('review', models.CharField(help_text='Maximum characters: 500', max_length=500, validators=[django.core.validators.MaxLengthValidator])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('isEdited', models.BooleanField(default=False)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
