# Generated by Django 3.2.8 on 2022-01-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220114_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='isEdited',
            new_name='is_edited',
        ),
    ]
